namespace NetWolf
{
    public static class BuiltinSymbolU
    {
        ///<summary>
        ///tests whether the Boolean expression bexpr is positive unate in the variables x1, x2, … .
        ///https://reference.wolfram.com/language/ref/UnateQ.html
        ///</summary>
        public static Engine UnateQ(this Engine en, string arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("UnateQ[" + arg0 + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///recovers an expression from a compressed string representation generated by Compress.
        ///https://reference.wolfram.com/language/ref/Uncompress.html
        ///</summary>
        public static Engine Uncompress(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("Uncompress[" + arg0 + "]", name);
        }

        ///<summary>
        ///wraps the head h around the expression produced before evaluating it.
        ///https://reference.wolfram.com/language/ref/Uncompress.html
        ///</summary>
        public static Engine Uncompress(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("Uncompress[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///displays with a bar under expr.
        ///https://reference.wolfram.com/language/ref/UnderBar.html
        ///</summary>
        public static Engine UnderBar(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnderBar[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents a number too small to represent explicitly on your computer system.
        ///https://reference.wolfram.com/language/ref/Underflow.html
        ///</summary>
        public static Engine Underflow(this Engine en, string? name = null)
        {
            return en.Execute("Underflow[]", name);
        }

        ///<summary>
        ///is an object that formats as .
        ///https://reference.wolfram.com/language/ref/Underoverscript.html
        ///</summary>
        public static Engine Underoverscript(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("Underoverscript[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///is the low‐level box representation for  in notebook expressions.
        ///https://reference.wolfram.com/language/ref/UnderoverscriptBox.html
        ///</summary>
        public static Engine UnderoverscriptBox(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UnderoverscriptBox[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///is an object that formats as .
        ///https://reference.wolfram.com/language/ref/Underscript.html
        ///</summary>
        public static Engine Underscript(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("Underscript[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///is the low‐level box representation for  in notebook expressions.
        ///https://reference.wolfram.com/language/ref/UnderscriptBox.html
        ///</summary>
        public static Engine UnderscriptBox(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UnderscriptBox[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///gives the value of the specified property for the undersea feature entity.
        ///https://reference.wolfram.com/language/ref/UnderseaFeatureData.html
        ///</summary>
        public static Engine UnderseaFeatureData(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UnderseaFeatureData[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///gives a list of property values for the specified undersea feature entities.
        ///https://reference.wolfram.com/language/ref/UnderseaFeatureData.html
        ///</summary>
        public static Engine UnderseaFeatureData(this Engine en, List<string> arg0, string arg1, string? name = null)
        {
            return en.Execute("UnderseaFeatureData[" + "{" + string.Join(',', arg0) + "}" + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///gives the specified annotation associated with the given property.
        ///https://reference.wolfram.com/language/ref/UnderseaFeatureData.html
        ///</summary>
        public static Engine UnderseaFeatureData(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UnderseaFeatureData[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///gives an undirected graph from the directed graph g.
        ///https://reference.wolfram.com/language/ref/UndirectedGraph.html
        ///</summary>
        public static Engine UndirectedGraph(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UndirectedGraph[" + arg0 + "]", name);
        }

        ///<summary>
        ///uses rules vw to specify the graph g.
        ///https://reference.wolfram.com/language/ref/UndirectedGraph.html
        ///</summary>
        public static Engine UndirectedGraph(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("UndirectedGraph[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///yields True if the graph g is an undirected graph and False otherwise.
        ///https://reference.wolfram.com/language/ref/UndirectedGraphQ.html
        ///</summary>
        public static Engine UndirectedGraphQ(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UndirectedGraphQ[" + arg0 + "]", name);
        }

        ///<summary>
        ///is an operator form that yields x≠y when applied to an expression x.
        ///https://reference.wolfram.com/language/ref/UnequalTo.html
        ///</summary>
        public static Engine UnequalTo(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnequalTo[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents the unevaluated form of expr when it appears as the argument to a function.
        ///https://reference.wolfram.com/language/ref/Unevaluated.html
        ///</summary>
        public static Engine Unevaluated(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("Unevaluated[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents a continuous uniform statistical distribution giving values between min and max.
        ///https://reference.wolfram.com/language/ref/UniformDistribution.html
        ///</summary>
        public static Engine UniformDistribution(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("UniformDistribution[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///represents a uniform distribution giving values between 0 and 1.
        ///https://reference.wolfram.com/language/ref/UniformDistribution.html
        ///</summary>
        public static Engine UniformDistribution(this Engine en, string? name = null)
        {
            return en.Execute("UniformDistribution[]", name);
        }

        ///<summary>
        ///represents a multivariate uniform distribution over the region {{xmin,xmax},{ymin,ymax},…}.
        ///https://reference.wolfram.com/language/ref/UniformDistribution.html
        ///</summary>
        public static Engine UniformDistribution(this Engine en, List<string> arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("UniformDistribution[" + "{" + string.Join(',', arg0) + "}" + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///represents a multivariate uniform distribution over the standard n dimensional unit hypercube.
        ///https://reference.wolfram.com/language/ref/UniformDistribution.html
        ///</summary>
        public static Engine UniformDistribution(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UniformDistribution[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents a uniform graph distribution on n-vertex, m-edge graphs.
        ///https://reference.wolfram.com/language/ref/UniformGraphDistribution.html
        ///</summary>
        public static Engine UniformGraphDistribution(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UniformGraphDistribution[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///gives the uniform polyhedron with the given name.
        ///https://reference.wolfram.com/language/ref/UniformPolyhedron.html
        ///</summary>
        public static Engine UniformPolyhedron(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UniformPolyhedron[" + arg0 + "]", name);
        }

        ///<summary>
        ///gives the uniform polyhedron with n sides of each face and m faces meeting at each vertex point.
        ///https://reference.wolfram.com/language/ref/UniformPolyhedron.html
        ///</summary>
        public static Engine UniformPolyhedron(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("UniformPolyhedron[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///rescales the uniform polyhedron by a factor r and rotates by an angle θ with respect to the z axis and angle ϕ with respect to the y axis.
        ///https://reference.wolfram.com/language/ref/UniformPolyhedron.html
        ///</summary>
        public static Engine UniformPolyhedron(this Engine en, List<string> arg0, string arg1, string? name = null)
        {
            return en.Execute("UniformPolyhedron[" + "{" + string.Join(',', arg0) + "}" + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///centers the uniform polyhedron at {x,y,z}.
        ///https://reference.wolfram.com/language/ref/UniformPolyhedron.html
        ///</summary>
        public static Engine UniformPolyhedron(this Engine en, List<string> arg0, List<string> arg1, string arg2, string? name = null)
        {
            return en.Execute("UniformPolyhedron[" + "{" + string.Join(',', arg0) + "}" + ", " + "{" + string.Join(',', arg1) + "}" + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///represents the distribution of a sum of n random variables uniformly distributed from 0 to 1.
        ///https://reference.wolfram.com/language/ref/UniformSumDistribution.html
        ///</summary>
        public static Engine UniformSumDistribution(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UniformSumDistribution[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents the distribution of a sum of n random variables uniformly distributed from min to max.
        ///https://reference.wolfram.com/language/ref/UniformSumDistribution.html
        ///</summary>
        public static Engine UniformSumDistribution(this Engine en, string arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("UniformSumDistribution[" + arg0 + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///terminates an external program started by Install, and removes Wolfram Language definitions set up by it.
        ///https://reference.wolfram.com/language/ref/Uninstall.html
        ///</summary>
        public static Engine Uninstall(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("Uninstall[" + arg0 + "]", name);
        }

        ///<summary>
        ///gives a sorted list of all the distinct elements that appear in any of the listi.
        ///https://reference.wolfram.com/language/ref/Union.html
        ///</summary>
        public static Engine Union(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("Union[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///gives a sorted version of a list, in which all duplicated elements have been dropped.
        ///https://reference.wolfram.com/language/ref/Union.html
        ///</summary>
        public static Engine Union(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("Union[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents an entity class containing all the distinct entities in all the classi.
        ///https://reference.wolfram.com/language/ref/UnionedEntityClass.html
        ///</summary>
        public static Engine UnionedEntityClass(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UnionedEntityClass[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///displays as x⊎y⊎….
        ///https://reference.wolfram.com/language/ref/UnionPlus.html
        ///</summary>
        public static Engine UnionPlus(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UnionPlus[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///generates a new symbol, whose name is of the form $nnn.
        ///https://reference.wolfram.com/language/ref/Unique.html
        ///</summary>
        public static Engine Unique(this Engine en, string? name = null)
        {
            return en.Execute("Unique[]", name);
        }

        ///<summary>
        ///generates a new symbol, with a name of the form x$nnn.
        ///https://reference.wolfram.com/language/ref/Unique.html
        ///</summary>
        public static Engine Unique(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("Unique[" + arg0 + "]", name);
        }

        ///<summary>
        ///generates a list of new symbols.
        ///https://reference.wolfram.com/language/ref/Unique.html
        ///</summary>
        public static Engine Unique(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("Unique[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///gives the elements for each listi that are not in any other list.
        ///https://reference.wolfram.com/language/ref/UniqueElements.html
        ///</summary>
        public static Engine UniqueElements(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("UniqueElements[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///uses test to determine whether pairs of elements should be considered equivalent.
        ///https://reference.wolfram.com/language/ref/UniqueElements.html
        ///</summary>
        public static Engine UniqueElements(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UniqueElements[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///gives True if m is a unitary matrix, and False otherwise.
        ///https://reference.wolfram.com/language/ref/UnitaryMatrixQ.html
        ///</summary>
        public static Engine UnitaryMatrixQ(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitaryMatrixQ[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents the unit box function, equal to 1 for  and 0 otherwise.
        ///https://reference.wolfram.com/language/ref/UnitBox.html
        ///</summary>
        public static Engine UnitBox(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitBox[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents the multidimensional unit box function, equal to 1 if  and 0 otherwise.
        ///https://reference.wolfram.com/language/ref/UnitBox.html
        ///</summary>
        public static Engine UnitBox(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UnitBox[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///attempts to convert the specified quantity to the specified targetunit.
        ///https://reference.wolfram.com/language/ref/UnitConvert.html
        ///</summary>
        public static Engine UnitConvert(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UnitConvert[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///converts the specified quantity to SI base units.
        ///https://reference.wolfram.com/language/ref/UnitConvert.html
        ///</summary>
        public static Engine UnitConvert(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitConvert[" + arg0 + "]", name);
        }

        ///<summary>
        ///returns a list of base dimensions associated with the specified unit.
        ///https://reference.wolfram.com/language/ref/UnitDimensions.html
        ///</summary>
        public static Engine UnitDimensions(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitDimensions[" + arg0 + "]", name);
        }

        ///<summary>
        ///gives 0 when x is zero, and 1 when x has any other numerical value.
        ///https://reference.wolfram.com/language/ref/Unitize.html
        ///</summary>
        public static Engine Unitize(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("Unitize[" + arg0 + "]", name);
        }

        ///<summary>
        ///tests whether data came from an autoregressive time series process with unit root.
        ///https://reference.wolfram.com/language/ref/UnitRootTest.html
        ///</summary>
        public static Engine UnitRootTest(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitRootTest[" + arg0 + "]", name);
        }

        ///<summary>
        ///returns the value of "property" for a given model.
        ///https://reference.wolfram.com/language/ref/UnitRootTest.html
        ///</summary>
        public static Engine UnitRootTest(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UnitRootTest[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///attempts to simplify the units of the specified quantity.
        ///https://reference.wolfram.com/language/ref/UnitSimplify.html
        ///</summary>
        public static Engine UnitSimplify(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitSimplify[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents the unit step function, equal to 0 for  and 1 for .
        ///https://reference.wolfram.com/language/ref/UnitStep.html
        ///</summary>
        public static Engine UnitStep(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitStep[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents the multidimensional unit step function which is 1 only if none of the  are negative.
        ///https://reference.wolfram.com/language/ref/UnitStep.html
        ///</summary>
        public static Engine UnitStep(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UnitStep[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///represents the unit triangle function on the interval  .
        ///https://reference.wolfram.com/language/ref/UnitTriangle.html
        ///</summary>
        public static Engine UnitTriangle(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitTriangle[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents the multidimensional unit triangle function on the interval .
        ///https://reference.wolfram.com/language/ref/UnitTriangle.html
        ///</summary>
        public static Engine UnitTriangle(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UnitTriangle[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///gives the two-dimensional unit vector in the k direction.
        ///https://reference.wolfram.com/language/ref/UnitVector.html
        ///</summary>
        public static Engine UnitVector(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitVector[" + arg0 + "]", name);
        }

        ///<summary>
        ///gives the n-dimensional unit vector in the k direction.
        ///https://reference.wolfram.com/language/ref/UnitVector.html
        ///</summary>
        public static Engine UnitVector(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UnitVector[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///represents a net layer that transforms integers between 1 and n into n-dimensional unit vectors.
        ///https://reference.wolfram.com/language/ref/UnitVectorLayer.html
        ///</summary>
        public static Engine UnitVectorLayer(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnitVectorLayer[" + arg0 + "]", name);
        }

        ///<summary>
        ///leaves the n to be inferred from context.
        ///https://reference.wolfram.com/language/ref/UnitVectorLayer.html
        ///</summary>
        public static Engine UnitVectorLayer(this Engine en, string? name = null)
        {
            return en.Execute("UnitVectorLayer[]", name);
        }

        ///<summary>
        ///returns properties of the universe based on the default model at specification defined by the time after the Big Bang, the distance to the comoving object, or the redshift of such an object.
        ///https://reference.wolfram.com/language/ref/UniverseModelData.html
        ///</summary>
        public static Engine UniverseModelData(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UniverseModelData[" + arg0 + "]", name);
        }

        ///<summary>
        ///returns properties of universe model at spec.
        ///https://reference.wolfram.com/language/ref/UniverseModelData.html
        ///</summary>
        public static Engine UniverseModelData(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UniverseModelData[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///returns the specified property at the time or distance spec for the universe model.
        ///https://reference.wolfram.com/language/ref/UniverseModelData.html
        ///</summary>
        public static Engine UniverseModelData(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UniverseModelData[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///gives the value of the specified property for the university entity.
        ///https://reference.wolfram.com/language/ref/UniversityData.html
        ///</summary>
        public static Engine UniversityData(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UniversityData[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///gives a list of property values for the specified university entities.
        ///https://reference.wolfram.com/language/ref/UniversityData.html
        ///</summary>
        public static Engine UniversityData(this Engine en, List<string> arg0, string arg1, string? name = null)
        {
            return en.Execute("UniversityData[" + "{" + string.Join(',', arg0) + "}" + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///gives the specified annotation associated with the given property.
        ///https://reference.wolfram.com/language/ref/UniversityData.html
        ///</summary>
        public static Engine UniversityData(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UniversityData[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///gives the total number of seconds since the beginning of January 1, 1970, in the GMT time zone.
        ///https://reference.wolfram.com/language/ref/UnixTime.html
        ///</summary>
        public static Engine UnixTime(this Engine en, string? name = null)
        {
            return en.Execute("UnixTime[]", name);
        }

        ///<summary>
        ///gives the Unix time specification corresponding to a date list.
        ///https://reference.wolfram.com/language/ref/UnixTime.html
        ///</summary>
        public static Engine UnixTime(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("UnixTime[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///gives the Unix time specification corresponding to a DateObject.
        ///https://reference.wolfram.com/language/ref/UnixTime.html
        ///</summary>
        public static Engine UnixTime(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnixTime[" + arg0 + "]", name);
        }

        ///<summary>
        ///takes the date string to contain the elements "ei".
        ///https://reference.wolfram.com/language/ref/UnixTime.html
        ///</summary>
        public static Engine UnixTime(this Engine en, string arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("UnixTime[" + arg0 + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///returns a tree of the same shape as tree in which the nodes and edges are displayed without labels.
        ///https://reference.wolfram.com/language/ref/UnlabeledTree.html
        ///</summary>
        public static Engine UnlabeledTree(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnlabeledTree[" + arg0 + "]", name);
        }

        ///<summary>
        ///takes ownership of memory wrapped in a "Managed" object, suitable for use in compiled code.
        ///https://reference.wolfram.com/language/ref/UnmanageObject.html
        ///</summary>
        public static Engine UnmanageObject(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnmanageObject[" + arg0 + "]", name);
        }

        ///<summary>
        ///removes the attribute Protected for the symbols si.
        ///https://reference.wolfram.com/language/ref/Unprotect.html
        ///</summary>
        public static Engine Unprotect(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("Unprotect[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///unprotects any symbols that are equal to or match any of the speci.
        ///https://reference.wolfram.com/language/ref/Unprotect.html
        ///</summary>
        public static Engine Unprotect(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("Unprotect[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///unregisters the external evaluator referenced by target for system sys so that it is not used by ExternalEvaluate and related functions.
        ///https://reference.wolfram.com/language/ref/UnregisterExternalEvaluator.html
        ///</summary>
        public static Engine UnregisterExternalEvaluator(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UnregisterExternalEvaluator[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///unregisters the external evaluator with the specified registration UUID.
        ///https://reference.wolfram.com/language/ref/UnregisterExternalEvaluator.html
        ///</summary>
        public static Engine UnregisterExternalEvaluator(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnregisterExternalEvaluator[" + arg0 + "]", name);
        }

        ///<summary>
        ///stops the sharing of the variables or functions si among parallel kernels.
        ///https://reference.wolfram.com/language/ref/UnsetShared.html
        ///</summary>
        public static Engine UnsetShared(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UnsetShared[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///stops the sharing of all variables and functions whose names match the string pattern patt.
        ///https://reference.wolfram.com/language/ref/UnsetShared.html
        ///</summary>
        public static Engine UnsetShared(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UnsetShared[" + arg0 + "]", name);
        }

        ///<summary>
        ///evaluates body and then test, repetitively, until test first gives True.
        ///https://reference.wolfram.com/language/ref/Until.html
        ///</summary>
        public static Engine Until(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("Until[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///displays as x↑y↑.
        ///https://reference.wolfram.com/language/ref/UpArrow.html
        ///</summary>
        public static Engine UpArrow(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UpArrow[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///displays as x⤒y⤒….
        ///https://reference.wolfram.com/language/ref/UpArrowBar.html
        ///</summary>
        public static Engine UpArrowBar(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UpArrowBar[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///displays as x⇅y⇅….
        ///https://reference.wolfram.com/language/ref/UpArrowDownArrow.html
        ///</summary>
        public static Engine UpArrowDownArrow(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UpArrowDownArrow[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///tells the Wolfram Language that hidden changes have been made that could affect values associated with a symbol.
        ///https://reference.wolfram.com/language/ref/Update.html
        ///</summary>
        public static Engine Update(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("Update[" + arg0 + "]", name);
        }

        ///<summary>
        ///specifies that the value of any symbol could be affected.
        ///https://reference.wolfram.com/language/ref/Update.html
        ///</summary>
        public static Engine Update(this Engine en, string? name = null)
        {
            return en.Execute("Update[]", name);
        }

        ///<summary>
        ///updates the given search index object.
        ///https://reference.wolfram.com/language/ref/UpdateSearchIndex.html
        ///</summary>
        public static Engine UpdateSearchIndex(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UpdateSearchIndex[" + arg0 + "]", name);
        }

        ///<summary>
        ///displays as x↕y↕….
        ///https://reference.wolfram.com/language/ref/UpDownArrow.html
        ///</summary>
        public static Engine UpDownArrow(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UpDownArrow[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///displays as x⥮y⥮….
        ///https://reference.wolfram.com/language/ref/UpEquilibrium.html
        ///</summary>
        public static Engine UpEquilibrium(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UpEquilibrium[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///yields True if all the characters in the string are uppercase letters, and yields False otherwise.
        ///https://reference.wolfram.com/language/ref/UpperCaseQ.html
        ///</summary>
        public static Engine UpperCaseQ(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UpperCaseQ[" + arg0 + "]", name);
        }

        ///<summary>
        ///displays as x↖y↖….
        ///https://reference.wolfram.com/language/ref/UpperLeftArrow.html
        ///</summary>
        public static Engine UpperLeftArrow(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UpperLeftArrow[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///displays as x↗y↗….
        ///https://reference.wolfram.com/language/ref/UpperRightArrow.html
        ///</summary>
        public static Engine UpperRightArrow(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UpperRightArrow[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///gives a matrix in which all but the upper triangular elements of m are replaced with zeros.
        ///https://reference.wolfram.com/language/ref/UpperTriangularize.html
        ///</summary>
        public static Engine UpperTriangularize(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UpperTriangularize[" + arg0 + "]", name);
        }

        ///<summary>
        ///replaces with zeros only the elements below the k subdiagonal of m.
        ///https://reference.wolfram.com/language/ref/UpperTriangularize.html
        ///</summary>
        public static Engine UpperTriangularize(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UpperTriangularize[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///converts the upper triangular matrix umat to a structured array.
        ///https://reference.wolfram.com/language/ref/UpperTriangularMatrix.html
        ///</summary>
        public static Engine UpperTriangularMatrix(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UpperTriangularMatrix[" + arg0 + "]", name);
        }

        ///<summary>
        ///gives True if m is upper triangular, and False otherwise.
        ///https://reference.wolfram.com/language/ref/UpperTriangularMatrixQ.html
        ///</summary>
        public static Engine UpperTriangularMatrixQ(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UpperTriangularMatrixQ[" + arg0 + "]", name);
        }

        ///<summary>
        ///gives True if m is upper triangular starting up from the k diagonal, and False otherwise.
        ///https://reference.wolfram.com/language/ref/UpperTriangularMatrixQ.html
        ///</summary>
        public static Engine UpperTriangularMatrixQ(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UpperTriangularMatrixQ[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///returns an upsampled version of the array by inserting  zeros between array elements.
        ///https://reference.wolfram.com/language/ref/Upsample.html
        ///</summary>
        public static Engine Upsample(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("Upsample[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///shifts array so that its first element moves to the position offset in the resulting array.
        ///https://reference.wolfram.com/language/ref/Upsample.html
        ///</summary>
        public static Engine Upsample(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("Upsample[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///inserts  elements of value val between array elements.
        ///https://reference.wolfram.com/language/ref/Upsample.html
        ///</summary>
        public static Engine Upsample(this Engine en, string arg0, string arg1, string arg2, string arg3, string? name = null)
        {
            return en.Execute("Upsample[" + arg0 + ", " + arg1 + ", " + arg2 + ", " + arg3 + "]", name);
        }

        ///<summary>
        ///displays as .
        ///https://reference.wolfram.com/language/ref/UpTee.html
        ///</summary>
        public static Engine UpTee(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("UpTee[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///displays as x↥y↥….
        ///https://reference.wolfram.com/language/ref/UpTeeArrow.html
        ///</summary>
        public static Engine UpTeeArrow(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("UpTeeArrow[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///is a symbolic specification that represents up to n objects or positions. If n objects or positions are available, all are used. If fewer are available, only those available are used.
        ///https://reference.wolfram.com/language/ref/UpTo.html
        ///</summary>
        public static Engine UpTo(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UpTo[" + arg0 + "]", name);
        }

        ///<summary>
        ///gives a list of transformation rules corresponding to all upvalues (values for g[…,f[…],…]) defined for the symbol f.
        ///https://reference.wolfram.com/language/ref/UpValues.html
        ///</summary>
        public static Engine UpValues(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UpValues[" + arg0 + "]", name);
        }

        ///<summary>
        ///is a symbolic representation of a URL.
        ///https://reference.wolfram.com/language/ref/URL.html
        ///</summary>
        public static Engine URL(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URL[" + arg0 + "]", name);
        }

        ///<summary>
        ///builds a URL with the specified path and query parameters and values parami and vali.
        ///https://reference.wolfram.com/language/ref/URLBuild.html
        ///</summary>
        public static Engine URLBuild(this Engine en, string arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("URLBuild[" + arg0 + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///builds a URL from the path components pathi.
        ///https://reference.wolfram.com/language/ref/URLBuild.html
        ///</summary>
        public static Engine URLBuild(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("URLBuild[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///builds a URL from a specification of a path and query parameters.
        ///https://reference.wolfram.com/language/ref/URLBuild.html
        ///</summary>
        public static Engine URLBuild(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("URLBuild[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///builds a URL from an association of components.
        ///https://reference.wolfram.com/language/ref/URLBuild.html
        ///</summary>
        public static Engine URLBuild(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLBuild[" + arg0 + "]", name);
        }

        ///<summary>
        ///decodes a URL-style percent-encoded string.
        ///https://reference.wolfram.com/language/ref/URLDecode.html
        ///</summary>
        public static Engine URLDecode(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLDecode[" + arg0 + "]", name);
        }

        ///<summary>
        ///represents a dispatcher for deployed URLs that specifies that URLs with relative paths matching the string patterns patti should give content represented by contenti.
        ///https://reference.wolfram.com/language/ref/URLDispatcher.html
        ///</summary>
        public static Engine URLDispatcher(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("URLDispatcher[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///downloads the content of the specified URL to a local temporary file.
        ///https://reference.wolfram.com/language/ref/URLDownload.html
        ///</summary>
        public static Engine URLDownload(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLDownload[" + arg0 + "]", name);
        }

        ///<summary>
        ///downloads the contents of the specified URLs to files in a local temporary directory.
        ///https://reference.wolfram.com/language/ref/URLDownload.html
        ///</summary>
        public static Engine URLDownload(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("URLDownload[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///downloads to a specified file.
        ///https://reference.wolfram.com/language/ref/URLDownload.html
        ///</summary>
        public static Engine URLDownload(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("URLDownload[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///downloads to a specified directory.
        ///https://reference.wolfram.com/language/ref/URLDownload.html
        ///</summary>
        public static Engine URLDownload(this Engine en, List<string> arg0, string arg1, string? name = null)
        {
            return en.Execute("URLDownload[" + "{" + string.Join(',', arg0) + "}" + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///returns only the element elem from the response.
        ///https://reference.wolfram.com/language/ref/URLDownload.html
        ///</summary>
        public static Engine URLDownload(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("URLDownload[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///returns an association of the values of the elements elemi.
        ///https://reference.wolfram.com/language/ref/URLDownload.html
        ///</summary>
        public static Engine URLDownload(this Engine en, string arg0, string arg1, List<string> arg2, string? name = null)
        {
            return en.Execute("URLDownload[" + arg0 + ", " + arg1 + ", " + "{" + string.Join(',', arg2) + "}" + "]", name);
        }

        ///<summary>
        ///submits the specified URL to be downloaded asynchronously to the file given.
        ///https://reference.wolfram.com/language/ref/URLDownloadSubmit.html
        ///</summary>
        public static Engine URLDownloadSubmit(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("URLDownloadSubmit[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///submits the specified URL, adding elements with names parami and values vali.
        ///https://reference.wolfram.com/language/ref/URLDownloadSubmit.html
        ///</summary>
        public static Engine URLDownloadSubmit(this Engine en, string arg0, string arg1, List<string> arg2, string? name = null)
        {
            return en.Execute("URLDownloadSubmit[" + arg0 + ", " + arg1 + ", " + "{" + string.Join(',', arg2) + "}" + "]", name);
        }

        ///<summary>
        ///converts "string" into a URL-style, percent-encoded ASCII string.
        ///https://reference.wolfram.com/language/ref/URLEncode.html
        ///</summary>
        public static Engine URLEncode(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLEncode[" + arg0 + "]", name);
        }

        ///<summary>
        ///executes the specified URL, importing whatever result is generated.
        ///https://reference.wolfram.com/language/ref/URLExecute.html
        ///</summary>
        public static Engine URLExecute(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLExecute[" + arg0 + "]", name);
        }

        ///<summary>
        ///executes the specified URL, adding elements with names parami and values vali.
        ///https://reference.wolfram.com/language/ref/URLExecute.html
        ///</summary>
        public static Engine URLExecute(this Engine en, string arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("URLExecute[" + arg0 + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///imports the result using the specified format.
        ///https://reference.wolfram.com/language/ref/URLExecute.html
        ///</summary>
        public static Engine URLExecute(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("URLExecute[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///executes a cloud object with current authentication settings.
        ///https://reference.wolfram.com/language/ref/URLExecute.html
        ///</summary>
        public static Engine URLExecute(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("URLExecute[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///expands a shortened "url".
        ///https://reference.wolfram.com/language/ref/URLExpand.html
        ///</summary>
        public static Engine URLExpand(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLExpand[" + arg0 + "]", name);
        }

        ///<summary>
        ///takes a well-formed URL and gives an association whose values correspond to the components of the URL.
        ///https://reference.wolfram.com/language/ref/URLParse.html
        ///</summary>
        public static Engine URLParse(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLParse[" + arg0 + "]", name);
        }

        ///<summary>
        ///returns only the specified component.
        ///https://reference.wolfram.com/language/ref/URLParse.html
        ///</summary>
        public static Engine URLParse(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("URLParse[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///returns only the specified component list.
        ///https://reference.wolfram.com/language/ref/URLParse.html
        ///</summary>
        public static Engine URLParse(this Engine en, string arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("URLParse[" + arg0 + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///decodes a URL-style query string into a list of key-value rules.
        ///https://reference.wolfram.com/language/ref/URLQueryDecode.html
        ///</summary>
        public static Engine URLQueryDecode(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLQueryDecode[" + arg0 + "]", name);
        }

        ///<summary>
        ///creates a URL-style query string from an association of keys and values.
        ///https://reference.wolfram.com/language/ref/URLQueryEncode.html
        ///</summary>
        public static Engine URLQueryEncode(this Engine en, string arg0, string arg1, string arg2, string? name = null)
        {
            return en.Execute("URLQueryEncode[" + arg0 + ", " + arg1 + ", " + arg2 + "]", name);
        }

        ///<summary>
        ///creates a query string from a list of rules.
        ///https://reference.wolfram.com/language/ref/URLQueryEncode.html
        ///</summary>
        public static Engine URLQueryEncode(this Engine en, List<string> arg0, string? name = null)
        {
            return en.Execute("URLQueryEncode[" + "{" + string.Join(',', arg0) + "}" + "]", name);
        }

        ///<summary>
        ///sends a request to a URL and reads back the response, returning it as a response object.
        ///https://reference.wolfram.com/language/ref/URLRead.html
        ///</summary>
        public static Engine URLRead(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLRead[" + arg0 + "]", name);
        }

        ///<summary>
        ///returns only the element elem from the response.
        ///https://reference.wolfram.com/language/ref/URLRead.html
        ///</summary>
        public static Engine URLRead(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("URLRead[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///returns an association of the values of the elements elemi.
        ///https://reference.wolfram.com/language/ref/URLRead.html
        ///</summary>
        public static Engine URLRead(this Engine en, string arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("URLRead[" + arg0 + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///sends the requests reqi in parallel, giving a list of the results obtained.
        ///https://reference.wolfram.com/language/ref/URLRead.html
        ///</summary>
        public static Engine URLRead(this Engine en, List<string> arg0, string arg1, string? name = null)
        {
            return en.Execute("URLRead[" + "{" + string.Join(',', arg0) + "}" + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///gives the total number of seconds to request one byte from the specified URL.
        ///https://reference.wolfram.com/language/ref/URLResponseTime.html
        ///</summary>
        public static Engine URLResponseTime(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLResponseTime[" + arg0 + "]", name);
        }

        ///<summary>
        ///gives the specified timing.
        ///https://reference.wolfram.com/language/ref/URLResponseTime.html
        ///</summary>
        public static Engine URLResponseTime(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("URLResponseTime[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///creates a shortened URL that redirects to "url".
        ///https://reference.wolfram.com/language/ref/URLShorten.html
        ///</summary>
        public static Engine URLShorten(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLShorten[" + arg0 + "]", name);
        }

        ///<summary>
        ///submits the specified URL to be executed asynchronously.
        ///https://reference.wolfram.com/language/ref/URLSubmit.html
        ///</summary>
        public static Engine URLSubmit(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("URLSubmit[" + arg0 + "]", name);
        }

        ///<summary>
        ///submits the specified URL, adding elements with names parami and values vali.
        ///https://reference.wolfram.com/language/ref/URLSubmit.html
        ///</summary>
        public static Engine URLSubmit(this Engine en, string arg0, List<string> arg1, string? name = null)
        {
            return en.Execute("URLSubmit[" + arg0 + ", " + "{" + string.Join(',', arg1) + "}" + "]", name);
        }

        ///<summary>
        ///submits the cloud object obj.
        ///https://reference.wolfram.com/language/ref/URLSubmit.html
        ///</summary>
        public static Engine URLSubmit(this Engine en, string arg0, string arg1, string? name = null)
        {
            return en.Execute("URLSubmit[" + arg0 + ", " + arg1 + "]", name);
        }

        ///<summary>
        ///evaluates expr, making use of a front end if necessary.
        ///https://reference.wolfram.com/language/ref/UsingFrontEnd.html
        ///</summary>
        public static Engine UsingFrontEnd(this Engine en, string arg0, string? name = null)
        {
            return en.Execute("UsingFrontEnd[" + arg0 + "]", name);
        }


    }
}